---
branches:
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
  - name: dev
    prerelease: true
plugins:
  - "semantic-release-gitmoji"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: "./mvnw versions:set -DnewVersion=${nextRelease.version}"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - pom.xml
      message: "🔖 Update `pom.xml` to `${nextRelease.version}` [skip release]\n\n${nextRelease.notes}"
